
# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: logistic.com
    EnableNodeOUs: true

    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
        SANS:
         - "localhost"
         - "127.0.0.1"

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  - Name: Shipper
    Domain: shipper.logistic.com
    SANS:
      - "localhost"
      - "127.0.0.1"
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  # ---------------------------------------------------------------------------
  # Org2: See "Org1" for full specification
  # ---------------------------------------------------------------------------
  - Name: Transporter
    Domain: transporter.logistic.com
    SANS:
      - "localhost"
      - "127.0.0.1"
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Warehouse
    Domain: warehouse.logistic.com
    SANS:
      - "localhost"
      - "127.0.0.1"
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Consignee
    Domain: consignee.logistic.com
    SANS:
      - "localhost"
      - "127.0.0.1"
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
