version: "2"

services:
    orderer.logistic.com:
        container_name: orderer.logistic.com
        extends:
            file: peer-base.yaml
            service: orderer-base
        volumes:
            - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
            - ../crypto-config/ordererOrganizations/logistic.com/orderers/orderer.logistic.com/msp:/var/hyperledger/orderer/msp
            - ../crypto-config/ordererOrganizations/logistic.com/orderers/orderer.logistic.com/tls/:/var/hyperledger/orderer/tls
        ports:
            - 7050:7050

    peer0.shipper.logistic.com:
        container_name: peer0.shipper.logistic.com
        extends:
            file: peer-base.yaml
            service: peer-base
        environment:
            - CORE_PEER_ID=peer0.shipper.logistic.com
            - CORE_PEER_ADDRESS=peer0.shipper.logistic.com:7051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
            - CORE_PEER_CHAINCODEADDRESS=peer0.shipper.logistic.com:7052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
            - CORE_PEER_LOCALMSPID=ShipperMSP
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.shipper.logistic.com:7051
        volumes:
            - /var/run/:/host/var/run/
            - ../crypto-config/peerOrganizations/shipper.logistic.com/peers/peer0.shipper.logistic.com/msp:/etc/hyperledger/fabric/msp
            - ../crypto-config/peerOrganizations/shipper.logistic.com/peers/peer0.shipper.logistic.com/tls:/etc/hyperledger/fabric/tls
        ports:
            - 7051:7051

    peer0.transporter.logistic.com:
        container_name: peer0.transporter.logistic.com
        extends:
            file: peer-base.yaml
            service: peer-base
        environment:
            - CORE_PEER_ID=peer0.transporter.logistic.com
            - CORE_PEER_ADDRESS=peer0.transporter.logistic.com:8051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
            - CORE_PEER_CHAINCODEADDRESS=peer0.transporter.logistic.com:8052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
            - CORE_PEER_LOCALMSPID=TransporterMSP
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.transporter.logistic.com:8051
        volumes:
            - /var/run/:/host/var/run/
            - ../crypto-config/peerOrganizations/transporter.logistic.com/peers/peer0.transporter.logistic.com/msp:/etc/hyperledger/fabric/msp
            - ../crypto-config/peerOrganizations/transporter.logistic.com/peers/peer0.transporter.logistic.com/tls:/etc/hyperledger/fabric/tls
        ports:
            - 8051:8051

    peer0.warehouse.logistic.com:
        container_name: peer0.warehouse.logistic.com
        extends:
            file: peer-base.yaml
            service: peer-base
        environment:
            - CORE_PEER_ID=peer0.warehouse.logistic.com
            - CORE_PEER_ADDRESS=peer0.warehouse.logistic.com:9051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
            - CORE_PEER_CHAINCODEADDRESS=peer0.warehouse.logistic.com:9052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
            - CORE_PEER_LOCALMSPID=WarehouseMSP
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.warehouse.logistic.com:9051
        volumes:
            - /var/run/:/host/var/run/
            - ../crypto-config/peerOrganizations/warehouse.logistic.com/peers/peer0.warehouse.logistic.com/msp:/etc/hyperledger/fabric/msp
            - ../crypto-config/peerOrganizations/warehouse.logistic.com/peers/peer0.warehouse.logistic.com/tls:/etc/hyperledger/fabric/tls
        ports:
            - 9051:9051

    peer0.consignee.logistic.com:
        container_name: peer0.consignee.logistic.com
        extends:
            file: peer-base.yaml
            service: peer-base
        environment:
            - CORE_PEER_ID=peer0.consignee.logistic.com
            - CORE_PEER_ADDRESS=peer0.consignee.logistic.com:10051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
            - CORE_PEER_CHAINCODEADDRESS=peer0.consignee.logistic.com:10052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
            - CORE_PEER_LOCALMSPID=ConsigneeMSP
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.consignee.logistic.com:10051
        volumes:
            - /var/run/:/host/var/run/
            - ../crypto-config/peerOrganizations/consignee.logistic.com/peers/peer0.consignee.logistic.com/msp:/etc/hyperledger/fabric/msp
            - ../crypto-config/peerOrganizations/consignee.logistic.com/peers/peer0.consignee.logistic.com/tls:/etc/hyperledger/fabric/tls
        ports:
            - 10051:10051